name: authentik-ci-web

on:
  push:
    branches:
      - main
      - next
      - version-*
  pull_request:
    branches:
      - main
      - version-*

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lint:
          - cmd: lint
          - cmd: lint:lockfile
          - cmd: tsc
          - cmd: prettier-check
          - cmd: lit-analyse
            extra_setup: |
              # lit-analyse doesn't understand path rewrites, so make it
              # belive it's an actual module
              cd node_modules/@goauthentik
              ln -s ../../src/ web
          - cmd: lint
        project:
          - web
          - tests/wdio
        exclude:
          - lint.cmd: lint:lockfile
            project: tests/wdio
          - lint.cmd: tsc
            project: tests/wdio
          - lint.cmd: lit-analyse
            project: tests/wdio
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ${{ matrix.lint.project }}/package.json
          cache: "npm"
          cache-dependency-path: ${{ matrix.lint.project }}/package-lock.json
      - working-directory: ${{ matrix.lint.project }}/
        run: npm ci
      - name: Generate API
        run: make gen-client-ts
      - name: Lint
        working-directory: ${{ matrix.lint.project }}/
        run: npm run ${{ matrix.lint.command }}
  ci-web-mark:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - run: echo mark
  build:
    needs:
      - ci-web-mark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: web/package.json
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - working-directory: web/
        run: npm ci
      - name: Generate API
        run: make gen-client-ts
      - name: build
        working-directory: web/
        run: npm run build
